### ISSUE TITLE
Disable start up/shut down messages

### ISSUE THREAD

**Issue by jontycg** [crflynn/celery-slack#1]
It's fantastic to have the ability to disable successful messages but an option to disable start up/shut down messages would be much appreciated.

**Comment by crflynn** [comment]
@jontycg I put together a PR with the features you requested. I'd like to test properly on a slack channel before I merge and push a new version. Should have time over the weekend.

**Comment by jontycg** [comment]
Awesome, thanks so much.

**Comment by crflynn** [comment]
@jontycg I just pushed version 0.2.0 with the features from #2 . https://pypi.org/project/celery-slack/0.2.0/

You should be able to disable celery/beat startup/shutdown messages with the following celery-slack options (they are True by default so you must explicitly disable them):

```python
options = {
    ...
    "show_startup": False,
    "show_shutdown": False,
    "show_beat": False,
    ...
}
```

Let me know if you run into any issues.
