### ISSUE TITLE
I can't update to celery-slack v0.4.0

### ISSUE THREAD

**Issue by UtsavPreet** [crflynn/celery-slack#24]
@crflynn I can't update to celery-slack v0.4.0 

throws the following error:

`Collecting celery-slack
  Using cached https://files.pythonhosted.org/packages/b3/c4/9c2c7e0e2633f2b573c1fcb7f0df333ece14f1af5a9d343b91649a2bef9e/celery_slack-0.4.0-py2.py3-none-any.whl
Requirement already satisfied: ephem<4.0,>=3.7 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from celery-slack) (3.7.7.0)
Collecting celery<3.2,<5.0,>=3.1,>=4.0 (from celery-slack)
  ERROR: Could not find a version that satisfies the requirement celery<3.2,<5.0,>=3.1,>=4.0 (from celery-slack) (from versions: 0.1.2, 0.1.4, 0.1.6, 0.1.7, 0.1.8, 0.1.10, 0.1.11, 0.1.12, 0.1.13, 0.1.14, 0.1.15, 0.2.0, 0.3.0, 0.3.7, 0.3.20, 0.4.0, 0.4.1, 0.6.0, 0.8.0, 0.8.1, 0.8.2, 0.8.3, 0.8.4, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.2.4, 2.2.5, 2.2.6, 2.2.7, 2.2.8, 2.2.9, 2.2.10, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.3.5, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.4.4, 2.4.5, 2.4.6, 2.4.7, 2.5.0, 2.5.1, 2.5.2, 2.5.3, 2.5.5, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6, 3.0.7, 3.0.8, 3.0.9, 3.0.10, 3.0.11, 3.0.12, 3.0.13, 3.0.14, 3.0.15, 3.0.16, 3.0.17, 3.0.18, 3.0.19, 3.0.20, 3.0.21, 3.0.22, 3.0.23, 3.0.24, 3.0.25, 3.1.0, 3.1.1, 3.1.2, 3.1.3, 3.1.4, 3.1.5, 3.1.6, 3.1.7, 3.1.8, 3.1.9, 3.1.10, 3.1.11, 3.1.12, 3.1.13, 3.1.14, 3.1.15, 3.1.16, 3.1.17, 3.1.18, 3.1.19, 3.1.20, 3.1.21, 3.1.22, 3.1.23, 3.1.24, 3.1.25, 3.1.26.post1, 3.1.26.post2, 4.0.0rc3, 4.0.0rc4, 4.0.0rc5, 4.0.0rc6, 4.0.0rc7, 4.0.0, 4.0.1, 4.0.2, 4.1.0, 4.1.1, 4.2.0rc1, 4.2.0rc2, 4.2.0rc3, 4.2.0rc4, 4.2.0, 4.2.1, 4.2.2, 4.3.0rc1, 4.3.0rc2, 4.3.0rc3, 4.3.0, 4.4.0rc1, 4.4.0rc2, 4.4.0rc3)
ERROR: No matching distribution found for celery<3.2,<5.0,>=3.1,>=4.0 (from celery-slack)
`
What changed between v0.3 and v0.4 ?

_Originally posted by @UtsavPreet in https://github.com/crflynn/celery-slack/issues/19#issuecomment-542160891_

**Comment by crflynn** [comment]
Hm looks like a weird issue with poetry and using multiple dependency version.

I have the celery dependency set to versions `celery = "~3.1 || ^4.0"`

but when it creates the setup.py file it is set to `celery>=3.1,<3.2,>=4.0,<5.0`, for which no versions are possible. I'll spend some time tonight trying to resolve this.

**Comment by crflynn** [comment]
try 0.4.1
