### ISSUE TITLE
Type Error string indices must be integers 

### ISSUE THREAD

**Issue by UtsavPreet** [crflynn/celery-slack#26]
I recently found this  sentry alert for your library. 

`Signal handler "<function slack_beat_init.<locals>.slack_beat_init_callback at 0x7fbacd9cb598>" raised: "TypeError('string indices must be integers',)"`

http://sentry.engineer.ai/share/issue/9e6772f82d7d4cbd94a16dfa1122becd/

**Comment by crflynn** [comment]
Can you share the beat schedule?

**Comment by UtsavPreet** [comment]
Where can i find that ? Assuming its a K8s based deployment.

**Comment by crflynn** [comment]
If you are using [celery beat](https://docs.celeryproject.org/en/latest/userguide/periodic-tasks.html#entries) to run scheduled tasks, you would create a schedule with a structure like [this](https://github.com/crflynn/celery-slack/blob/master/tests/celeryapp/schedule.py#L36).

That error indicates the schedule is not able to be parsed by the beat initialization slack message generator.

**Comment by UtsavPreet** [comment]
`@app.on_after_configure.connect
def setup_periodic_tasks(sender, **kwargs):
    sender.add_periodic_task(
        crontab(minute='30', hour='0'),
        update_do_pricing.s()
    )`

This is how I'm defining my periodic tasks.

**Comment by crflynn** [comment]
I'm having a tough time reproducing this on my end. Here is the example code I have using the same decorator you have. The result is that it adds the dummy method to the rest of the config-defined schedule:

```python
"""The celery app."""
import logging
import os

from celery import Celery
from celery.beat import crontab

from celery_slack import Slackify
from .schedule import get_schedule

try:
    from ..secret import slack_webhook
except Exception:
    slack_webhook = os.environ["SLACK_WEBHOOK"]


logging.basicConfig(level="INFO")


schedule = get_schedule()

app = Celery("schedule")
app.config_from_object("tests.celeryapp.config")


@app.task
def dummy():
    pass


@app.on_after_configure.connect
def setup_periodic_tasks(sender, **kwargs):
    sender.add_periodic_task(crontab(minute='30', hour='0'), dummy.s())


options = {
    "flower_base_url": "https://flower.example.com",
    "webhook": slack_webhook,
    "beat_schedule": schedule,
    "show_beat": True,
    "slack_request_timeout": 3,
    "show_broker": True,
}

logging.info("Creating celery-slack object.")
slack_app = Slackify(app, **options)
logging.info("Created celery-slack object.")


if __name__ == "__main__":
    app.start()
```

This makes it through the beat init callback just fine, and the added task is present in the schedule displayed:

<img width="665" alt="Screen Shot 2019-10-19 at 10 02 02 AM" src="https://user-images.githubusercontent.com/16403734/67146300-aa045d00-f257-11e9-88bf-d08adecdf6f8.png">

Do you have any other context you can provide?
