### ISSUE TITLE
periodic_task not being sent to slack.

### ISSUE THREAD

**Issue by esirK** [crflynn/celery-slack#32]
Firstly, thank you for an awesome too.

I have a small issue where normal `@task` are successfully sent to slack but `@periodic_task` are not being sent. Any ideas why this might be happening?

**Comment by palvarezcordoba** [comment]
What Celery version are you using? If you are using the `periodic_task` decorator I guess you're using Celery 2.x, maybe that's the problem, lol. If possible, update to the latest Celery version available.
You could instead fork celery-slack and adapt the code to whatever Celery version you're using. To see how celery-slack does its work, see this: https://github.com/crflynn/celery-slack/blob/master/celery_slack/slackify.py#L109
Check also this: https://github.com/celery/celery/blob/v2.0.0/celery/decorators.py

**Comment by esirK** [comment]
> What Celery version are you using? If you are using the `periodic_task` decorator I guess you're using Celery 2.x, maybe that's the problem, lol. If possible, update to the latest Celery version available.
> You could instead fork celery-slack and adapt the code to whatever Celery version you're using. To see how celery-slack does its work, see this: https://github.com/crflynn/celery-slack/blob/master/celery_slack/slackify.py#L109
> Check also this: https://github.com/celery/celery/blob/v2.0.0/celery/decorators.py

Hey @palvarezcordoba 
Thank you for your feedback. I'm currently using celery 4.x and I did manage to get it working by utilising `app.conf.beat_schedule` for scheduling the periodic tasks. I didn't have to do any other changes to this package. 
I'll close this for now.
