### ISSUE TITLE
Slack messages for failure to send message to broker 

### ISSUE THREAD

**Issue by crflynn** [crflynn/celery-slack#4]
Referencing [this comment](https://github.com/crflynn/celery-slack/issues/3#issuecomment-396822588) which requested Slack message for when no connection is available to the broker and the task fails to send.

> another question, how can i catch Exception from Celery's broker and send to slack.
> like my broker(e.g. RabbitMQ ) suddenly shutdown, but it could not send message to Slack though i got the connection error in logs

**Comment by crflynn** [comment]
Repeating my comment from #3:

> Most of the Slack interactions take place using Celery's [signals](http://docs.celeryproject.org/en/latest/userguide/signals.html), but the task success/failure Slack messages are actually set up by decorating the Task class's on_success() and on_failure()methods because the signals don't expose all the information needed in the Slack messages.
> 
> I see signals for before_task_publish and after_task_publish but I don't think they would handle this particular issue. I might consider decorating the methods for these actions with a try-except and in the except clause posting the message, but I'll think more about it this week.

**Comment by crflynn** [comment]
It might be necessary to wrap a [function from the kombu library](https://github.com/celery/kombu/blob/75695205f6e7af8e7e9178e010debc3871b19106/kombu/connection.py#L409) to do this.

**Comment by wzyonggege** [comment]
A simple way probably can handle this issue, I open a new celery Queue to listen broker's connection status so that I could receive that exceptions.

**Comment by crflynn** [comment]
Started working on this. I think I can wrap the [connection retry function in kombu](https://github.com/celery/kombu/blob/75695205f6e7af8e7e9178e010debc3871b19106/kombu/connection.py#L402) to post broker disconnect/reconnect.

**Comment by crflynn** [comment]
@wzyonggege: In 0.3.0 you can enable broker disconnection/reconnection messages using the option:

```python
options = {
    ...
    "show_broker": True
    ...
}
